#version: '3.8'

services:
  arcatierra-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcatierra-webapp-new
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    networks:
      - vps-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcatierra.rule=Host(`arcatierra.dabychos.com`)"
      - "traefik.http.routers.arcatierra.entrypoints=websecure"
      - "traefik.http.routers.arcatierra.tls=true"
      - "traefik.http.routers.arcatierra.tls.certresolver=letsencrypt"
      - "traefik.http.services.arcatierra.loadbalancer.server.port=3000"

networks:
  vps-net:
    external: true