// src/data/categorias.ts
// AUTOGENERATED FROM 'productos.csv' to ensure consistency.

export interface CategoriaSEO {
  metaTitle: string;
  metaDescription: string;
}

const categorySlugs = [
  "canastas-de-frutas-y-verduras-agroecologicas",
  "aceites-naturales",
  "granos-y-cereales-integrales",
  "proteinas-regenerativas",
  "endulzantes",
  "proteina-animal",
  "granos-semillas-y-cereales",
  "cafe-cacao-y-chocolate",
  "especias",
  "abarrotes",
  "mermeladas-y-untables",
  "pastas",
  "infusiones-y-te",
  "galletas-harinas-y-pan",
  "huevo-y-lacteos",
  "aceites-y-grasas",
  "condimentos",
  "cacao-y-chocolate",
  "te-y-hierbas-medicinales",
  "maiz",
  "frutas-y-verduras-a-granel"
];

// Helper to convert slug to Title Case
function slugToTitle(slug: string): string {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

const categoriasData: { [key: string]: CategoriaSEO } = {};
categorySlugs.forEach(slug => {
  const title = slugToTitle(slug);
  categoriasData[title] = {
    metaTitle: title, // Default SEO meta title
    metaDescription: `Descubre nuestros productos en la categoría ${title}.` // Default SEO meta description
  };
});

export const categoriasSEO = categoriasData;

// Función para obtener datos SEO de una categoría por nombre exacto
export function getSEODataByName(categoryName: string): CategoriaSEO | undefined {
  return categoriasSEO[categoryName];
}

export default categoriasSEO;
