// src/data/categorias.ts
// AUTOGENERATED FROM 'productos.csv' to ensure consistency.

export interface CategoriaSEO {
  metaTitle: string;
  metaDescription: string;
}

const categorySlugs = [
  "canastas-agroecologicas",
  "cafe-cacao-chocolate",
  "especias-condimentos",
  "endulzantes-naturales",
  "frutas-verduras",
  "granos-cereales",
  "huevo-lacteos",
  "infusiones-naturales",
  "maiz",
  "mermeladas-untables",
  "harinas-pastas",
  "pan-galletas",
  "proteinas-regenerativas"
];

// Helper to convert slug to Title Case
function slugToTitle(slug: string): string {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

const categoriasData: { [key: string]: CategoriaSEO } = {};
categorySlugs.forEach(slug => {
  const title = slugToTitle(slug);
  categoriasData[title] = {
    metaTitle: title, // Default SEO meta title
    metaDescription: `Descubre nuestros productos en la categoría ${title}.` // Default SEO meta description
  };
});

export const categoriasSEO = categoriasData;

// Función para obtener datos SEO de una categoría por nombre exacto
export function getSEODataByName(categoryName: string): CategoriaSEO | undefined {
  return categoriasSEO[categoryName];
}

export default categoriasSEO;
